services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: lyria
      DATABASE_USER: lyria
      DATABASE_PASSWORD: lyria

  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: lyria
      POSTGRES_USER: lyria
      POSTGRES_PASSWORD: lyria
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql


volumes:
  postgres_data: